name: PCK.AUTOMIC_SCP
source: ae
binaries:
- object: RESOURCES/LIBS/PCK.AUTOMIC_SCP.PRV.STORE
  resources: 
  - name: SCPTOOL.JAR
    type: BINARY
    path: tools/scp-tool/target/scp-tool.jar
    version: 1.1.3
- object: RESOURCES/PCK.AUTOMIC_SCP.PRV.CUSTOM_TYPES
  timestamp: disabled
  resources:
  - name: ARTIFACTSOURCE#SCP
    type: TEXT
    path: ara/types/artifact/Artifact_SCP_1.0.0.xml
    version: 1.0.0